version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: agrotani-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: agrotani_db
    ports:
      - "5432:5432"
    volumes:
      - agrotani-pgdata:/var/lib/postgresql/data
    networks:
      - agrotani-network

volumes:
  agrotani-pgdata:
    name: agrotani-pgdata

networks:
  agrotani-network:
    name: agrotani-network